name: CI
on: [push, pull_request]

jobs:
  ios-latest:
    runs-on: macOS-latest

    steps:
      - name: Clone
        uses: actions/checkout@v1

      - name: Dependencies
        run: |
          brew update
          brew install cmake

      - name: Build
        run: |
          cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_SYSTEM_PROCESSOR=arm64 .
          make
          
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ios_static_lib
          path: libwhisper.a
